image: "rust:latest"

stages:
    - test
    - build
    - release
    - deploy

test:cargo:check:
    stage: test
    script:
        - cargo check

test:fmt:
    stage: test
    script:
        - rustup toolchain install nightly
        - rustup component add rustfmt --toolchain nightly
        - rustfmt --check src/*.rs src/sequences/*.rs

build:cargo:
    stage: build
    script:
        - rustc --version && cargo --version
        - cargo build

release:cargo:
    stage: release
    script:
        - cargo build --release
        - strip target/release/numerus
    artifacts:
        paths:
            - target/release/numerus
    only:
        - master
        - tags