image: "rust:latest"

stages:
    - test
    - build
    - release

test:cargo:check:
    stage: test
    script:
        - cargo check

test:fmt:
    stage: test
    script:
        - rustup component add rustfmt --toolchain 1.36.0-x86_64-unknown-linux-gnu
        - rustfmt --check src/*.rs

build:cargo:
    stage: build
    script:
        - rustc --version && cargo --version
        - cargo build

release:cargo:
    stage: release
    script:
        - cargo build --release
        - strip target/release/numerus
    artifacts:
        paths:
            - target/release/numerus
    only:
        - master
        - tags
